### [] 이용하기

In [1]:
import pandas as pd
df_raw = pd.read_csv('exam.csv')
df=df_raw.head(10)
df

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58
4   5       2     25    80      65
5   6       2     50    89      98
6   7       2     80    90      45
7   8       2     90    78      25
8   9       3     20    98      15
9  10       3     50    98      45

In [2]:
df['nclass']

0    1
1    1
2    1
3    1
4    2
5    2
6    2
7    2
8    3
9    3
Name: nclass, dtype: int64

In [3]:
df['nclass']==1

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: nclass, dtype: bool

논리 연산자를 사용하면 조건 여부를 True / False로 확인할 수 있음

In [4]:
df[df['nclass']==1]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58

In [5]:
df[df['front']>=80]

   id  nclass  front  back  design
6   7       2     80    90      45
7   8       2     90    78      25

In [6]:
df[(df['nclass'])==1 &(df['front']>=50)]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60

In [7]:
df[(df['front']<50) | (df['back'] < 50)]

   id  nclass  front  back  design
2   3       1     45    86      78
3   4       1     30    98      58
4   5       2     25    80      65
8   9       3     20    98      15

여러 조건을 동시에 충족하고 싶으면 & 사용,
하나 이상 충족하는 행을 추출하려면 | 사용

In [8]:
df['id']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [9]:
df['nclass']

0    1
1    1
2    1
3    1
4    2
5    2
6    2
7    2
8    3
9    3
Name: nclass, dtype: int64

In [10]:
df[['id', 'nclass']]

   id  nclass
0   1       1
1   2       1
2   3       1
3   4       1
4   5       2
5   6       2
6   7       2
7   8       2
8   9       3
9  10       3

[] 하고 변수명 지정하면 열 추출 가능!

In [11]:
df['id']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [12]:
df[['id']]

   id
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

변수를 1개만 추출하면서 데이터프레임 자료 구조를 유지하려면 변수명을 []로 한 번 더 감싸면 된다.

열 1개만 추출 : 시리즈 자료 구조로 바뀜

열 2개 이상 추출하면 df 구조 유지

In [13]:
df[df['nclass']==1]['front']

0    50
1    60
2    45
3    30
Name: front, dtype: int64

In [17]:
df[df['nclass']==1][['front', 'back']]

   front  back
0     50    98
1     60    97
2     45    86
3     30    98

여러 열을 추출하려면 [] 를 이용해서 변수명 나열

In [18]:
df.groupby('nclass').agg(front=('front', 'mean'), back =('back', 'mean'))

        front   back
nclass
1       46.25  94.75
2       61.25  84.25
3       35.00  98.00

In [19]:
df.groupby('nclass')[['front', 'back']].mean()

        front   back
nclass
1       46.25  94.75
2       61.25  84.25
3       35.00  98.00

pandas와 []를 함께 사용할 수도 있고, pandas만 사용할 수 있음

같이 쓰는 게 더 깔끔해보임

### df.loc[] 이용하기

In [22]:
df = pd.DataFrame({'var1': [1,2,3], 'var2' : [4,5,6]})
df

   var1  var2
0     1     4
1     2     5
2     3     6

In [24]:
df = pd.DataFrame({'var1': [1,2,3], 'var2' : [4,5,6]}, index=['kim', 'lee', 'park'])
df

      var1  var2
kim      1     4
lee      2     5
park     3     6

위 예제를 통해 index 를 이용하면 인덱스 문자열을 지정할 수 있다는 걸 확인할 수 있음

In [25]:
df.loc['kim']

var1    1
var2    4
Name: kim, dtype: int64

In [27]:
df.loc[['kim', 'park']]

      var1  var2
kim      1     4
park     3     6

In [28]:
df.loc['lee', 'var1']

np.int64(2)

In [29]:
df.loc[['kim', 'lee'], 'var2']

kim    4
lee    5
Name: var2, dtype: int64

In [31]:
#df.loc[, 'var1']

위의 코드는 에러가 발생함!!

[]에 쉼표를 입력하고 그 앞에는 행을 가리키는 인덱스 문자열, 뒤에는 열을 가리키는 변수명을 입력한다.

df.loc[]를 이용해 열을 추출할 때 반드시 행 추출 기준도 같이 입력해야 함

In [32]:
df.loc[:, 'var1']

kim     1
lee     2
park    3
Name: var1, dtype: int64

모든 행을 추출하려면 :를 입력

In [33]:
df = df_raw.copy()
df

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
2    3       1     45    86      78
3    4       1     30    98      58
4    5       2     25    80      65
5    6       2     50    89      98
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [34]:
df.loc[0]

id         1
nclass     1
front     50
back      98
design    50
Name: 0, dtype: int64

In [35]:
df.loc[[0]]

   id  nclass  front  back  design
0   1       1     50    98      50

In [36]:
df.loc[[0,3,5]]

   id  nclass  front  back  design
0   1       1     50    98      50
3   4       1     30    98      58
5   6       2     50    89      98

In [37]:
df.loc[0:3]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58

In [38]:
df.loc[:3]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58

In [39]:
df.loc[5:]

    id  nclass  front  back  design
5    6       2     50    89      98
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [40]:
df.loc[:]

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
2    3       1     45    86      78
3    4       1     30    98      58
4    5       2     25    80      65
5    6       2     50    89      98
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

슬라이싱 : ':'를 이용해 연속된 행을 추출하는 작업

1. : 앞에 값 입력 안 하면 첫번째 행부터 추출

2. : 뒤에 값 입력 안 하면 마지막 행까지 추출

3. : 앞뒤에 아무 값도 입력하지 않으면 모든 행 추출

In [41]:
df.loc[2, :]

id         3
nclass     1
front     45
back      86
design    78
Name: 2, dtype: int64

In [42]:
# df.loc[:, 2]

df.loc[]은 열 추출 불가. 행 추출만 가능

In [43]:
df.loc[df['nclass']==1]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58

In [45]:
df.loc[df['nclass']==1, ['front', 'back']]

   front  back
0     50    98
1     60    97
2     45    86
3     30    98

In [46]:
df.loc[0:3, 'front']

0    50
1    60
2    45
3    30
Name: front, dtype: int64

df.loc에 쉼표를 이용하면 조건을 충족하는 행에서 열을 추출할 수 있음

In [48]:
# 프론트 점수 50점 초과하는 행 추출
df.query('front > 50')

    id  nclass  front  back  design
1    2       1     60    97      60
6    7       2     80    90      45
7    8       2     90    78      25
10  11       3     65    65      65
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [50]:
df[df['front']>50]

    id  nclass  front  back  design
1    2       1     60    97      60
6    7       2     80    90      45
7    8       2     90    78      25
10  11       3     65    65      65
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [51]:
df.loc[df['front']>50]

    id  nclass  front  back  design
1    2       1     60    97      60
6    7       2     80    90      45
7    8       2     90    78      25
10  11       3     65    65      65
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

### df.iloc[] 이용하기

쉼표를 기준으로 앞에는 행, 뒤에는 열 기준으로 입력

인덱스 문자열 말고 인덱스 번호를 입력한다.

In [52]:
df.iloc[0]

id         1
nclass     1
front     50
back      98
design    50
Name: 0, dtype: int64

In [53]:
df.iloc[[0]]

   id  nclass  front  back  design
0   1       1     50    98      50

In [54]:
df.iloc[[0,3,5]]

   id  nclass  front  back  design
0   1       1     50    98      50
3   4       1     30    98      58
5   6       2     50    89      98

In [55]:
df.loc[1:5]

   id  nclass  front  back  design
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58
4   5       2     25    80      65
5   6       2     50    89      98

In [56]:
df.iloc[1:5]

   id  nclass  front  back  design
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58
4   5       2     25    80      65

df.loc[x : y] = x행  이상 y행 이하 추출

df.iloc[x : y] = x행 이상 y행 미만 추출

In [58]:
df_label = pd.DataFrame({'var1' : [1,2,3], 'var2' : [4,5,6]}, index=['kim', 'lee', 'park'])
df_label

      var1  var2
kim      1     4
lee      2     5
park     3     6

In [59]:
# df_label.loc[0]

In [60]:
df_label.iloc[0]

var1    1
var2    4
Name: kim, dtype: int64

df.iloc는 인덱스 번호로 행 추출 가능

In [61]:
df.iloc[:, [1,3]]

    nclass  back
0        1    98
1        1    97
2        1    86
3        1    98
4        2    80
5        2    89
6        2    90
7        2    78
8        3    98
9        3    98
10       3    65
11       3    85
12       4    98
13       4    87
14       4    56
15       4    98
16       5    68
17       5    78
18       5    68
19       5    83

In [62]:
df.iloc[[0,1], [2,3]]

   front  back
0     50    98
1     60    97

In [63]:
# df.iloc[df['nclass]==1]

df.iloc[]는 조건을 지정해서 행을 추출할 수 없음

행 추출 인덱스 : df.loc[]는 문자열과 번호 <-> df.iloc[]는 번호

열 추출 인덱스 : df.loc[]는 문자열 <-> df.iloc[]는 번호

조건 지정해서 행 추출 : df.loc[]는 가능 <-> df.iloc[]는 불가능

연속된 행 추출 x:y 의미 : df.loc[]는 이상&이하 <-> df.iloc[]는 이상&미만