### [] 이용하기

In [1]:
import pandas as pd
df_raw = pd.read_csv('exam.csv')
df=df_raw.head(10)
df

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58
4   5       2     25    80      65
5   6       2     50    89      98
6   7       2     80    90      45
7   8       2     90    78      25
8   9       3     20    98      15
9  10       3     50    98      45

In [2]:
df['nclass']

0    1
1    1
2    1
3    1
4    2
5    2
6    2
7    2
8    3
9    3
Name: nclass, dtype: int64

In [3]:
df['nclass']==1

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: nclass, dtype: bool

논리 연산자를 사용하면 조건 여부를 True / False로 확인할 수 있음

In [4]:
df[df['nclass']==1]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58

In [5]:
df[df['front']>=80]

   id  nclass  front  back  design
6   7       2     80    90      45
7   8       2     90    78      25

In [6]:
df[(df['nclass'])==1 &(df['front']>=50)]

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60

In [7]:
df[(df['front']<50) | (df['back'] < 50)]

   id  nclass  front  back  design
2   3       1     45    86      78
3   4       1     30    98      58
4   5       2     25    80      65
8   9       3     20    98      15

여러 조건을 동시에 충족하고 싶으면 & 사용,
하나 이상 충족하는 행을 추출하려면 | 사용

In [8]:
df['id']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [9]:
df['nclass']

0    1
1    1
2    1
3    1
4    2
5    2
6    2
7    2
8    3
9    3
Name: nclass, dtype: int64

In [10]:
df[['id', 'nclass']]

   id  nclass
0   1       1
1   2       1
2   3       1
3   4       1
4   5       2
5   6       2
6   7       2
7   8       2
8   9       3
9  10       3

[] 하고 변수명 지정하면 열 추출 가능!

In [11]:
df['id']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [12]:
df[['id']]

   id
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

변수를 1개만 추출하면서 데이터프레임 자료 구조를 유지하려면 변수명을 []로 한 번 더 감싸면 된다.

열 1개만 추출 : 시리즈 자료 구조로 바뀜

열 2개 이상 추출하면 df 구조 유지

In [13]:
df[df['nclass']==1]['front']

0    50
1    60
2    45
3    30
Name: front, dtype: int64

In [17]:
df[df['nclass']==1][['front', 'back']]

   front  back
0     50    98
1     60    97
2     45    86
3     30    98

여러 열을 추출하려면 [] 를 이용해서 변수명 나열

In [18]:
df.groupby('nclass').agg(front=('front', 'mean'), back =('back', 'mean'))

        front   back
nclass
1       46.25  94.75
2       61.25  84.25
3       35.00  98.00

In [19]:
df.groupby('nclass')[['front', 'back']].mean()

        front   back
nclass
1       46.25  94.75
2       61.25  84.25
3       35.00  98.00

pandas와 []를 함께 사용할 수도 있고, pandas만 사용할 수 있음

같이 쓰는 게 더 깔끔해보임