In [1]:
import pandas as pd
exam = pd.read_csv('exam.csv')
exam

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
2    3       1     45    86      78
3    4       1     30    98      58
4    5       2     25    80      65
5    6       2     50    89      98
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

### 조건에 맞는 데이터만 추출하기

In [2]:
exam.query('nclass==1')

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60
2   3       1     45    86      78
3   4       1     30    98      58

In [3]:
exam.query('nclass!=1')

    id  nclass  front  back  design
4    5       2     25    80      65
5    6       2     50    89      98
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [4]:
exam.query('front>50')

    id  nclass  front  back  design
1    2       1     60    97      60
6    7       2     80    90      45
7    8       2     90    78      25
10  11       3     65    65      65
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [5]:
exam.query('front<50')

    id  nclass  front  back  design
2    3       1     45    86      78
3    4       1     30    98      58
4    5       2     25    80      65
8    9       3     20    98      15
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12

In [6]:
exam.query('back >=50')

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
2    3       1     45    86      78
3    4       1     30    98      58
4    5       2     25    80      65
5    6       2     50    89      98
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
12  13       4     46    98      65
13  14       4     48    87      12
14  15       4     75    56      78
15  16       4     58    98      65
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [7]:
exam.query('back <=80')

    id  nclass  front  back  design
4    5       2     25    80      65
7    8       2     90    78      25
10  11       3     65    65      65
14  15       4     75    56      78
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87

### 여러 조건을 충족하는 행 추출하기

In [8]:
exam.query('nclass ==1 & front >=50')

   id  nclass  front  back  design
0   1       1     50    98      50
1   2       1     60    97      60

### 여러 조건 중 하나 이상 충족하는 행 추출하기

In [11]:
exam.query('front >=90 | back >=90')

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
3    4       1     30    98      58
6    7       2     80    90      45
7    8       2     90    78      25
8    9       3     20    98      15
9   10       3     50    98      45
12  13       4     46    98      65
15  16       4     58    98      65

### 목록에 해당하는 행 추출하기

In [13]:
exam.query('nclass == 1 | nclass==3 | nclass==5')

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
2    3       1     45    86      78
3    4       1     30    98      58
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

In [14]:
exam.query('nclass in [1, 3, 5]')

    id  nclass  front  back  design
0    1       1     50    98      50
1    2       1     60    97      60
2    3       1     45    86      78
3    4       1     30    98      58
8    9       3     20    98      15
9   10       3     50    98      45
10  11       3     65    65      65
11  12       3     45    85      32
16  17       5     65    68      98
17  18       5     80    78      90
18  19       5     89    68      87
19  20       5     78    83      58

### 추출한 행으로 데이터 만들기

In [17]:
nclass1 = exam.query('nclass==1')
nclass2 = exam.query('nclass==2')

In [18]:
nclass1['front'].mean()

np.float64(46.25)

In [19]:
nclass2['front'].mean()

np.float64(61.25)

### 변수 추출하기

In [20]:
exam['front']

0     50
1     60
2     45
3     30
4     25
5     50
6     80
7     90
8     20
9     50
10    65
11    45
12    46
13    48
14    75
15    58
16    65
17    80
18    89
19    78
Name: front, dtype: int64

In [21]:
exam['nclass']

0     1
1     1
2     1
3     1
4     2
5     2
6     2
7     2
8     3
9     3
10    3
11    3
12    4
13    4
14    4
15    4
16    5
17    5
18    5
19    5
Name: nclass, dtype: int64

### 여러 변수 추출하기

In [22]:
exam[['nclass', 'front', 'back']]

    nclass  front  back
0        1     50    98
1        1     60    97
2        1     45    86
3        1     30    98
4        2     25    80
5        2     50    89
6        2     80    90
7        2     90    78
8        3     20    98
9        3     50    98
10       3     65    65
11       3     45    85
12       4     46    98
13       4     48    87
14       4     75    56
15       4     58    98
16       5     65    68
17       5     80    78
18       5     89    68
19       5     78    83

### 변수 제거하기

In [23]:
exam.drop(columns='front')

    id  nclass  back  design
0    1       1    98      50
1    2       1    97      60
2    3       1    86      78
3    4       1    98      58
4    5       2    80      65
5    6       2    89      98
6    7       2    90      45
7    8       2    78      25
8    9       3    98      15
9   10       3    98      45
10  11       3    65      65
11  12       3    85      32
12  13       4    98      65
13  14       4    87      12
14  15       4    56      78
15  16       4    98      65
16  17       5    68      98
17  18       5    78      90
18  19       5    68      87
19  20       5    83      58

### 여러 변수 제거하기

In [24]:
exam.drop(columns=['front', 'back'])

    id  nclass  design
0    1       1      50
1    2       1      60
2    3       1      78
3    4       1      58
4    5       2      65
5    6       2      98
6    7       2      45
7    8       2      25
8    9       3      15
9   10       3      45
10  11       3      65
11  12       3      32
12  13       4      65
13  14       4      12
14  15       4      78
15  16       4      65
16  17       5      98
17  18       5      90
18  19       5      87
19  20       5      58

### pandas 함수 조절하기

In [25]:
exam.query('nclass==1')['front']

0    50
1    60
2    45
3    30
Name: front, dtype: int64

In [26]:
exam.query('front>=50')[['id','front']].head(10)

    id  front
0    1     50
1    2     60
5    6     50
6    7     80
7    8     90
9   10     50
10  11     65
14  15     75
15  16     58
16  17     65

### 가독성 있게 코드 줄 바꾸기

In [27]:
exam.query('front >=50')\
[['id', 'front']]\
.head(10)

    id  front
0    1     50
1    2     60
5    6     50
6    7     80
7    8     90
9   10     50
10  11     65
14  15     75
15  16     58
16  17     65